language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
#  - 3.4

#  - pypy

branches:
  only:
    - master

install: pip install .

script: CFLAGS="-O0 -ggdb" python runtests.py -vv

matrix:
  allow_failures:
    - python: pypy
